# Generated by Django 2.2.3 on 2020-03-09 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_admin_employee_employeeskill_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='role',
            field=models.PositiveSmallIntegerField(choices=[(1, 'admin'), (2, 'employee'), (3, 'employee')], null=True),
        ),
    ]
