# Generated by Django 2.2.3 on 2020-03-13 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200309_2352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='role',
            field=models.PositiveSmallIntegerField(choices=[(1, 'admin'), (2, 'manager'), (3, 'employee')], null=True),
        ),
    ]
