# Generated by Django 3.0.5 on 2020-04-26 07:04

from django.db import migrations, models
import django.db.models.deletion
import recruting.main.models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0001_initial'),
        ('main', '0004_auto_20200313_0639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='skills.Position'),
        ),
        migrations.AlterField(
            model_name='manager',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='skills.Category'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='role',
            field=models.PositiveSmallIntegerField(choices=[(1, 'admin'), (2, 'manager'), (3, 'employee')], null=True, validators=[recruting.main.models.validate_role]),
        ),
    ]
