# Generated by Django 3.0.5 on 2020-04-26 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20200426_0704'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='admin_photo'),
        ),
        migrations.AddField(
            model_name='employee',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='employee_photo'),
        ),
        migrations.AddField(
            model_name='manager',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='manager_photo'),
        ),
    ]
