# Generated by Django 3.0.5 on 2020-04-27 04:34

from django.db import migrations, models
import recruting.main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20200426_0711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='admin_photo', validators=[recruting.main.models.validate_extension, recruting.main.models.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='employee',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='employee_photo', validators=[recruting.main.models.validate_extension, recruting.main.models.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='manager',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='manager_photo', validators=[recruting.main.models.validate_extension, recruting.main.models.validate_file_size]),
        ),
    ]
