# Generated by Django 2.2.3 on 2020-03-09 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_mes', models.CharField(max_length=255)),
                ('to_mes', models.CharField(max_length=255)),
                ('mess', models.CharField(max_length=1024)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
                'ordering': ('date',),
            },
        ),
    ]
